# fly.toml app configuration file generated for snowy-butterfly-1680 on 2023-06-04T12:18:54-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "snowy-butterfly-1680"
primary_region = "yyz"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
